//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Alarms = new HashSet<Alarm>();
            this.ControlOrders = new HashSet<ControlOrder>();
            this.DailyConsumptions = new HashSet<DailyConsumption>();
            this.HistoricalDailyConsumptions = new HashSet<HistoricalDailyConsumption>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.MeterReads = new HashSet<MeterRead>();
            this.PendingCharges = new HashSet<PendingCharge>();
            this.PendingClients = new HashSet<PendingClient>();
            this.Transactions = new HashSet<Transaction>();
            this.TwelveMonthsConsumptions = new HashSet<TwelveMonthsConsumption>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string MeterNumber { get; set; }
        public int TariffID { get; set; }
        public int MeterTypeID { get; set; }
        public string CardID { get; set; }
        public int NoOfCards { get; set; }
        public int ChargeCount { get; set; }
        public decimal ContractedPower { get; set; }
        public int IssuanceState { get; set; }
        public System.DateTime InstallDate { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public int StatusByte { get; set; }
        public string Password { get; set; }
        public long SameClientID { get; set; }
        public string AliasName { get; set; }
        public System.DateTime LastOnlineDate { get; set; }
        public string NIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alarm> Alarms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlOrder> ControlOrders { get; set; }
        public virtual MeterType MeterType { get; set; }
        public virtual PricePlan PricePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyConsumption> DailyConsumptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricalDailyConsumption> HistoricalDailyConsumptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterRead> MeterReads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingCharge> PendingCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingClient> PendingClients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TwelveMonthsConsumption> TwelveMonthsConsumptions { get; set; }
    }
}
