//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceDetail()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public decimal InvoiceNumber { get; set; }
        public long ClientID { get; set; }
        public decimal ChargeValue { get; set; }
        public decimal Deposit { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public long SameClientID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public int Status { get; set; }
        public int NumberOfTries { get; set; }
        public string RefusionReason { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual PendingCharge PendingCharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
