//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeterType()
        {
            this.Customers = new HashSet<Customer>();
            this.PendingClients = new HashSet<PendingClient>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public int Category { get; set; }
        public short AlarmLimit { get; set; }
        public short CutoffLimit { get; set; }
        public short MaxCurrent { get; set; }
        public short NumOfWires { get; set; }
        public short CTRatio { get; set; }
        public short UncutStartPeriod { get; set; }
        public short UnCutEndPeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingClient> PendingClients { get; set; }
    }
}
