//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PricePlan()
        {
            this.Customers = new HashSet<Customer>();
            this.PendingClients = new HashSet<PendingClient>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Period1Price { get; set; }
        public int Period2Price { get; set; }
        public int Period3Price { get; set; }
        public int Period4Price { get; set; }
        public int InitialCharge { get; set; }
        public int Period5Price { get; set; }
        public int Period6Price { get; set; }
        public int Period7Price { get; set; }
        public int StartPeriod1 { get; set; }
        public int StartPeriod2 { get; set; }
        public int StartPeriod3 { get; set; }
        public int StartPeriod4 { get; set; }
        public int StartPeriod5 { get; set; }
        public int StartPeriod6 { get; set; }
        public int StartPeriod7 { get; set; }
        public int RecalculationLimit1 { get; set; }
        public int RecalculationLimit2 { get; set; }
        public int RecalculationLimit3 { get; set; }
        public long AddedPayment1 { get; set; }
        public long AddedPayment2 { get; set; }
        public long AddedPayment3 { get; set; }
        public int KiloWattAlarm { get; set; }
        public int CustomerService1 { get; set; }
        public int CustomerService2 { get; set; }
        public int CustomerService3 { get; set; }
        public int CustomerService4 { get; set; }
        public int CustomerService5 { get; set; }
        public int CustomerService6 { get; set; }
        public int CustomerService7 { get; set; }
        public int CommercialDamgha { get; set; }
        public int NoConsumptionFee { get; set; }
        public int NoOfTariffs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingClient> PendingClients { get; set; }
        public virtual TariffsPrice TariffsPrice { get; set; }
        public virtual TariffsPrice TariffsPrice1 { get; set; }
        public virtual TariffsPrice TariffsPrice2 { get; set; }
        public virtual TariffsPrice TariffsPrice3 { get; set; }
        public virtual TariffsPrice TariffsPrice4 { get; set; }
        public virtual TariffsPrice TariffsPrice5 { get; set; }
        public virtual TariffsPrice TariffsPrice6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
