//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemovedDailyConsumption
    {
        public long ClientID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Consumption { get; set; }
        public decimal TotalConsumption { get; set; }
    }
}
