//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool AddUserPrivilege { get; set; }
        public bool AddRolePrivilege { get; set; }
        public bool AddTariffPrivilege { get; set; }
        public bool AddMeterTypePrivilege { get; set; }
        public bool AddClientPrivilege { get; set; }
        public bool ChargeClientPrivilege { get; set; }
        public bool ClientQueryPrivilege { get; set; }
        public bool EditRolePrivilege { get; set; }
        public bool EditUserPrivilege { get; set; }
        public bool EditUsersPasswordPrivilege { get; set; }
        public bool ReportsPrivilege { get; set; }
        public bool ReadMeterPrivilege { get; set; }
        public bool MeterReadingsEnquiryPrivilege { get; set; }
        public bool EditClientPrivilege { get; set; }
        public bool CloseRelay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
