//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public long ClientID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public int Operation { get; set; }
        public System.DateTime Date { get; set; }
        public int TariffID { get; set; }
        public decimal Balance { get; set; }
        public decimal OnCardBalance { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual InvoiceDetail InvoiceDetail { get; set; }
        public virtual PricePlan PricePlan { get; set; }
        public virtual User User { get; set; }
    }
}
